# Generated by Django 3.1 on 2020-10-22 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photogram', '0002_auto_20201022_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hotel_Main_Img',
            new_name='image',
        ),
    ]
